### ISSUE TITLE
Loved the creativity flowing out of the project! 

### ISSUE THREAD

**Issue by sevdas** [fac21/mc-mc-leaf-it-out#39]
Well done on responsibility and accessibility, you may be able to boost the accessibility of your app by simply adding alt attribute to your images. 

<img width="365" alt="Screenshot 2021-05-07 at 10 22 05" src="https://user-images.githubusercontent.com/63476393/117428701-38b1fb00-af1e-11eb-99a5-a0f6323c91a2.png">

Here is more insight in MDN about alt attributes and their usability: 

The alt attribute holds a text description of the image, which isn't mandatory but is incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt-text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by michael-devlin** [comment]
resolved via Antonio's suggestion
